# Generated by Django 4.0.4 on 2022-05-11 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulos_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='categoria',
            field=models.CharField(choices=[('Hard', 'Hardware'), ('Soft', 'Software'), ('Ins', 'Insumos'), ('Serv', 'Servicio'), ('Var', 'Varios')], default='x', max_length=4),
        ),
    ]
